package ym.nemo233.bookstore.sqlite;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOKCASE".
*/
public class BookcaseDao extends AbstractDao<Bookcase, Long> {

    public static final String TABLENAME = "BOOKCASE";

    /**
     * Properties of entity Bookcase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Tag = new Property(1, String.class, "tag", false, "TAG");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Sort = new Property(3, Integer.class, "sort", false, "SORT");
        public final static Property Newest = new Property(4, String.class, "newest", false, "NEWEST");
        public final static Property Chapter = new Property(5, Integer.class, "chapter", false, "CHAPTER");
        public final static Property PageNumber = new Property(6, Integer.class, "pageNumber", false, "PAGE_NUMBER");
        public final static Property CacheState = new Property(7, Integer.class, "cacheState", false, "CACHE_STATE");
        public final static Property BiId = new Property(8, Long.class, "biId", false, "BI_ID");
    }

    private DaoSession daoSession;


    public BookcaseDao(DaoConfig config) {
        super(config);
    }
    
    public BookcaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOKCASE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TAG\" TEXT UNIQUE ," + // 1: tag
                "\"NAME\" TEXT," + // 2: name
                "\"SORT\" INTEGER," + // 3: sort
                "\"NEWEST\" TEXT," + // 4: newest
                "\"CHAPTER\" INTEGER," + // 5: chapter
                "\"PAGE_NUMBER\" INTEGER," + // 6: pageNumber
                "\"CACHE_STATE\" INTEGER," + // 7: cacheState
                "\"BI_ID\" INTEGER);"); // 8: biId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOKCASE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Bookcase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(2, tag);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer sort = entity.getSort();
        if (sort != null) {
            stmt.bindLong(4, sort);
        }
 
        String newest = entity.getNewest();
        if (newest != null) {
            stmt.bindString(5, newest);
        }
 
        Integer chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindLong(6, chapter);
        }
 
        Integer pageNumber = entity.getPageNumber();
        if (pageNumber != null) {
            stmt.bindLong(7, pageNumber);
        }
 
        Integer cacheState = entity.getCacheState();
        if (cacheState != null) {
            stmt.bindLong(8, cacheState);
        }
 
        Long biId = entity.getBiId();
        if (biId != null) {
            stmt.bindLong(9, biId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Bookcase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(2, tag);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer sort = entity.getSort();
        if (sort != null) {
            stmt.bindLong(4, sort);
        }
 
        String newest = entity.getNewest();
        if (newest != null) {
            stmt.bindString(5, newest);
        }
 
        Integer chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindLong(6, chapter);
        }
 
        Integer pageNumber = entity.getPageNumber();
        if (pageNumber != null) {
            stmt.bindLong(7, pageNumber);
        }
 
        Integer cacheState = entity.getCacheState();
        if (cacheState != null) {
            stmt.bindLong(8, cacheState);
        }
 
        Long biId = entity.getBiId();
        if (biId != null) {
            stmt.bindLong(9, biId);
        }
    }

    @Override
    protected final void attachEntity(Bookcase entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Bookcase readEntity(Cursor cursor, int offset) {
        Bookcase entity = new Bookcase( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tag
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // sort
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // newest
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // chapter
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // pageNumber
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // cacheState
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // biId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Bookcase entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTag(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSort(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setNewest(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setChapter(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setPageNumber(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setCacheState(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setBiId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Bookcase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Bookcase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Bookcase entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBooksInformationDao().getAllColumns());
            builder.append(" FROM BOOKCASE T");
            builder.append(" LEFT JOIN BOOKS_INFORMATION T0 ON T.\"BI_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Bookcase loadCurrentDeep(Cursor cursor, boolean lock) {
        Bookcase entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BooksInformation book = loadCurrentOther(daoSession.getBooksInformationDao(), cursor, offset);
        entity.setBook(book);

        return entity;    
    }

    public Bookcase loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Bookcase> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Bookcase> list = new ArrayList<Bookcase>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Bookcase> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Bookcase> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
