package ym.nemo233.bookstore.sqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_INFORMATION".
*/
public class BookInformationDao extends AbstractDao<BookInformation, Long> {

    public static final String TABLENAME = "BOOK_INFORMATION";

    /**
     * Properties of entity BookInformation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdentifyCode = new Property(1, String.class, "identifyCode", false, "IDENTIFY_CODE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Auth = new Property(3, String.class, "auth", false, "AUTH");
        public final static Property Instr = new Property(4, String.class, "instr", false, "INSTR");
        public final static Property ImageUrl = new Property(5, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property ClassName = new Property(6, String.class, "className", false, "CLASS_NAME");
        public final static Property Status = new Property(7, String.class, "status", false, "STATUS");
        public final static Property SourceUrl = new Property(8, String.class, "sourceUrl", false, "SOURCE_URL");
        public final static Property SiteName = new Property(9, String.class, "siteName", false, "SITE_NAME");
        public final static Property CurrentChapter = new Property(10, Integer.class, "currentChapter", false, "CURRENT_CHAPTER");
        public final static Property Sort = new Property(11, Integer.class, "sort", false, "SORT");
        public final static Property Newest = new Property(12, String.class, "newest", false, "NEWEST");
        public final static Property Upt = new Property(13, String.class, "upt", false, "UPT");
    }

    private DaoSession daoSession;


    public BookInformationDao(DaoConfig config) {
        super(config);
    }
    
    public BookInformationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_INFORMATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"IDENTIFY_CODE\" TEXT UNIQUE ," + // 1: identifyCode
                "\"NAME\" TEXT," + // 2: name
                "\"AUTH\" TEXT," + // 3: auth
                "\"INSTR\" TEXT," + // 4: instr
                "\"IMAGE_URL\" TEXT," + // 5: imageUrl
                "\"CLASS_NAME\" TEXT," + // 6: className
                "\"STATUS\" TEXT," + // 7: status
                "\"SOURCE_URL\" TEXT," + // 8: sourceUrl
                "\"SITE_NAME\" TEXT," + // 9: siteName
                "\"CURRENT_CHAPTER\" INTEGER," + // 10: currentChapter
                "\"SORT\" INTEGER," + // 11: sort
                "\"NEWEST\" TEXT," + // 12: newest
                "\"UPT\" TEXT);"); // 13: upt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_INFORMATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookInformation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String identifyCode = entity.getIdentifyCode();
        if (identifyCode != null) {
            stmt.bindString(2, identifyCode);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String auth = entity.getAuth();
        if (auth != null) {
            stmt.bindString(4, auth);
        }
 
        String instr = entity.getInstr();
        if (instr != null) {
            stmt.bindString(5, instr);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(6, imageUrl);
        }
 
        String className = entity.getClassName();
        if (className != null) {
            stmt.bindString(7, className);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(8, status);
        }
 
        String sourceUrl = entity.getSourceUrl();
        if (sourceUrl != null) {
            stmt.bindString(9, sourceUrl);
        }
 
        String siteName = entity.getSiteName();
        if (siteName != null) {
            stmt.bindString(10, siteName);
        }
 
        Integer currentChapter = entity.getCurrentChapter();
        if (currentChapter != null) {
            stmt.bindLong(11, currentChapter);
        }
 
        Integer sort = entity.getSort();
        if (sort != null) {
            stmt.bindLong(12, sort);
        }
 
        String newest = entity.getNewest();
        if (newest != null) {
            stmt.bindString(13, newest);
        }
 
        String upt = entity.getUpt();
        if (upt != null) {
            stmt.bindString(14, upt);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookInformation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String identifyCode = entity.getIdentifyCode();
        if (identifyCode != null) {
            stmt.bindString(2, identifyCode);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String auth = entity.getAuth();
        if (auth != null) {
            stmt.bindString(4, auth);
        }
 
        String instr = entity.getInstr();
        if (instr != null) {
            stmt.bindString(5, instr);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(6, imageUrl);
        }
 
        String className = entity.getClassName();
        if (className != null) {
            stmt.bindString(7, className);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(8, status);
        }
 
        String sourceUrl = entity.getSourceUrl();
        if (sourceUrl != null) {
            stmt.bindString(9, sourceUrl);
        }
 
        String siteName = entity.getSiteName();
        if (siteName != null) {
            stmt.bindString(10, siteName);
        }
 
        Integer currentChapter = entity.getCurrentChapter();
        if (currentChapter != null) {
            stmt.bindLong(11, currentChapter);
        }
 
        Integer sort = entity.getSort();
        if (sort != null) {
            stmt.bindLong(12, sort);
        }
 
        String newest = entity.getNewest();
        if (newest != null) {
            stmt.bindString(13, newest);
        }
 
        String upt = entity.getUpt();
        if (upt != null) {
            stmt.bindString(14, upt);
        }
    }

    @Override
    protected final void attachEntity(BookInformation entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BookInformation readEntity(Cursor cursor, int offset) {
        BookInformation entity = new BookInformation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // identifyCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // auth
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // instr
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // imageUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // className
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // status
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sourceUrl
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // siteName
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // currentChapter
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // sort
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // newest
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // upt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookInformation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdentifyCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuth(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setInstr(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImageUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setClassName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStatus(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSourceUrl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSiteName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCurrentChapter(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setSort(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setNewest(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setUpt(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BookInformation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BookInformation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookInformation entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
