package ym.nemo233.bookstore.sqlite;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ym.nemo233.bookstore.sqlite.Bookcase;
import ym.nemo233.bookstore.sqlite.BookcaseClassifyCache;
import ym.nemo233.bookstore.sqlite.BooksInformation;
import ym.nemo233.bookstore.sqlite.BooksSite;
import ym.nemo233.bookstore.sqlite.Chapter;
import ym.nemo233.bookstore.sqlite.PopularBooks;
import ym.nemo233.bookstore.sqlite.WebsiteSource;

import ym.nemo233.bookstore.sqlite.BookcaseDao;
import ym.nemo233.bookstore.sqlite.BookcaseClassifyCacheDao;
import ym.nemo233.bookstore.sqlite.BooksInformationDao;
import ym.nemo233.bookstore.sqlite.BooksSiteDao;
import ym.nemo233.bookstore.sqlite.ChapterDao;
import ym.nemo233.bookstore.sqlite.PopularBooksDao;
import ym.nemo233.bookstore.sqlite.WebsiteSourceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookcaseDaoConfig;
    private final DaoConfig bookcaseClassifyCacheDaoConfig;
    private final DaoConfig booksInformationDaoConfig;
    private final DaoConfig booksSiteDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig popularBooksDaoConfig;
    private final DaoConfig websiteSourceDaoConfig;

    private final BookcaseDao bookcaseDao;
    private final BookcaseClassifyCacheDao bookcaseClassifyCacheDao;
    private final BooksInformationDao booksInformationDao;
    private final BooksSiteDao booksSiteDao;
    private final ChapterDao chapterDao;
    private final PopularBooksDao popularBooksDao;
    private final WebsiteSourceDao websiteSourceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookcaseDaoConfig = daoConfigMap.get(BookcaseDao.class).clone();
        bookcaseDaoConfig.initIdentityScope(type);

        bookcaseClassifyCacheDaoConfig = daoConfigMap.get(BookcaseClassifyCacheDao.class).clone();
        bookcaseClassifyCacheDaoConfig.initIdentityScope(type);

        booksInformationDaoConfig = daoConfigMap.get(BooksInformationDao.class).clone();
        booksInformationDaoConfig.initIdentityScope(type);

        booksSiteDaoConfig = daoConfigMap.get(BooksSiteDao.class).clone();
        booksSiteDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        popularBooksDaoConfig = daoConfigMap.get(PopularBooksDao.class).clone();
        popularBooksDaoConfig.initIdentityScope(type);

        websiteSourceDaoConfig = daoConfigMap.get(WebsiteSourceDao.class).clone();
        websiteSourceDaoConfig.initIdentityScope(type);

        bookcaseDao = new BookcaseDao(bookcaseDaoConfig, this);
        bookcaseClassifyCacheDao = new BookcaseClassifyCacheDao(bookcaseClassifyCacheDaoConfig, this);
        booksInformationDao = new BooksInformationDao(booksInformationDaoConfig, this);
        booksSiteDao = new BooksSiteDao(booksSiteDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        popularBooksDao = new PopularBooksDao(popularBooksDaoConfig, this);
        websiteSourceDao = new WebsiteSourceDao(websiteSourceDaoConfig, this);

        registerDao(Bookcase.class, bookcaseDao);
        registerDao(BookcaseClassifyCache.class, bookcaseClassifyCacheDao);
        registerDao(BooksInformation.class, booksInformationDao);
        registerDao(BooksSite.class, booksSiteDao);
        registerDao(Chapter.class, chapterDao);
        registerDao(PopularBooks.class, popularBooksDao);
        registerDao(WebsiteSource.class, websiteSourceDao);
    }
    
    public void clear() {
        bookcaseDaoConfig.clearIdentityScope();
        bookcaseClassifyCacheDaoConfig.clearIdentityScope();
        booksInformationDaoConfig.clearIdentityScope();
        booksSiteDaoConfig.clearIdentityScope();
        chapterDaoConfig.clearIdentityScope();
        popularBooksDaoConfig.clearIdentityScope();
        websiteSourceDaoConfig.clearIdentityScope();
    }

    public BookcaseDao getBookcaseDao() {
        return bookcaseDao;
    }

    public BookcaseClassifyCacheDao getBookcaseClassifyCacheDao() {
        return bookcaseClassifyCacheDao;
    }

    public BooksInformationDao getBooksInformationDao() {
        return booksInformationDao;
    }

    public BooksSiteDao getBooksSiteDao() {
        return booksSiteDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public PopularBooksDao getPopularBooksDao() {
        return popularBooksDao;
    }

    public WebsiteSourceDao getWebsiteSourceDao() {
        return websiteSourceDao;
    }

}
