package ym.nemo233.bookstore.sqlite;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ym.nemo233.bookstore.sqlite.BookInformation;
import ym.nemo233.bookstore.sqlite.Chapter;
import ym.nemo233.bookstore.sqlite.WebSite;
import ym.nemo233.bookstore.sqlite.HistoryQuery;

import ym.nemo233.bookstore.sqlite.BookInformationDao;
import ym.nemo233.bookstore.sqlite.ChapterDao;
import ym.nemo233.bookstore.sqlite.WebSiteDao;
import ym.nemo233.bookstore.sqlite.HistoryQueryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookInformationDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig webSiteDaoConfig;
    private final DaoConfig historyQueryDaoConfig;

    private final BookInformationDao bookInformationDao;
    private final ChapterDao chapterDao;
    private final WebSiteDao webSiteDao;
    private final HistoryQueryDao historyQueryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookInformationDaoConfig = daoConfigMap.get(BookInformationDao.class).clone();
        bookInformationDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        webSiteDaoConfig = daoConfigMap.get(WebSiteDao.class).clone();
        webSiteDaoConfig.initIdentityScope(type);

        historyQueryDaoConfig = daoConfigMap.get(HistoryQueryDao.class).clone();
        historyQueryDaoConfig.initIdentityScope(type);

        bookInformationDao = new BookInformationDao(bookInformationDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        webSiteDao = new WebSiteDao(webSiteDaoConfig, this);
        historyQueryDao = new HistoryQueryDao(historyQueryDaoConfig, this);

        registerDao(BookInformation.class, bookInformationDao);
        registerDao(Chapter.class, chapterDao);
        registerDao(WebSite.class, webSiteDao);
        registerDao(HistoryQuery.class, historyQueryDao);
    }
    
    public void clear() {
        bookInformationDaoConfig.clearIdentityScope();
        chapterDaoConfig.clearIdentityScope();
        webSiteDaoConfig.clearIdentityScope();
        historyQueryDaoConfig.clearIdentityScope();
    }

    public BookInformationDao getBookInformationDao() {
        return bookInformationDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public WebSiteDao getWebSiteDao() {
        return webSiteDao;
    }

    public HistoryQueryDao getHistoryQueryDao() {
        return historyQueryDao;
    }

}
