package ym.nemo233.bookstore.sqlite;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEBSITE_SOURCE".
*/
public class WebsiteSourceDao extends AbstractDao<WebsiteSource, Long> {

    public static final String TABLENAME = "WEBSITE_SOURCE";

    /**
     * Properties of entity WebsiteSource.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Website = new Property(2, String.class, "website", false, "WEBSITE");
        public final static Property Selected = new Property(3, Boolean.class, "selected", false, "SELECTED");
    }


    public WebsiteSourceDao(DaoConfig config) {
        super(config);
    }
    
    public WebsiteSourceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEBSITE_SOURCE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"WEBSITE\" TEXT," + // 2: website
                "\"SELECTED\" INTEGER);"); // 3: selected
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEBSITE_SOURCE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WebsiteSource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String website = entity.getWebsite();
        if (website != null) {
            stmt.bindString(3, website);
        }
 
        Boolean selected = entity.getSelected();
        if (selected != null) {
            stmt.bindLong(4, selected ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WebsiteSource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String website = entity.getWebsite();
        if (website != null) {
            stmt.bindString(3, website);
        }
 
        Boolean selected = entity.getSelected();
        if (selected != null) {
            stmt.bindLong(4, selected ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WebsiteSource readEntity(Cursor cursor, int offset) {
        WebsiteSource entity = new WebsiteSource( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // website
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // selected
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WebsiteSource entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWebsite(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSelected(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WebsiteSource entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WebsiteSource entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WebsiteSource entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
